package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Log;
import at.fhv.itm14.fhvgis.persistence.cayenne.Track;
import at.fhv.itm14.fhvgis.persistence.cayenne.User;

/**
 * Class _Device was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Device extends CayenneDataObject {

    public static final String TOKEN_PROPERTY = "token";
    public static final String LOG_ARRAY_PROPERTY = "logArray";
    public static final String TO_USER_PROPERTY = "toUser";
    public static final String TRACK_ARRAY_PROPERTY = "trackArray";

    public static final String ID_PK_COLUMN = "id";

    public void setToken(String token) {
        writeProperty("token", token);
    }
    public String getToken() {
        return (String)readProperty("token");
    }

    public void addToLogArray(Log obj) {
        addToManyTarget("logArray", obj, true);
    }
    public void removeFromLogArray(Log obj) {
        removeToManyTarget("logArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Log> getLogArray() {
        return (List<Log>)readProperty("logArray");
    }


    public void setToUser(User toUser) {
        setToOneTarget("toUser", toUser, true);
    }

    public User getToUser() {
        return (User)readProperty("toUser");
    }


    public void addToTrackArray(Track obj) {
        addToManyTarget("trackArray", obj, true);
    }
    public void removeFromTrackArray(Track obj) {
        removeToManyTarget("trackArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Track> getTrackArray() {
        return (List<Track>)readProperty("trackArray");
    }


}
