package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Poi;

/**
 * Class _Geofence was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Geofence extends CayenneDataObject {

    public static final String POSITIONS_PROPERTY = "positions";
    public static final String TO_POI_PROPERTY = "toPoi";

    public static final String ID_PK_COLUMN = "id";

    public void setPositions(String positions) {
        writeProperty("positions", positions);
    }
    public String getPositions() {
        return (String)readProperty("positions");
    }

    public void setToPoi(Poi toPoi) {
        setToOneTarget("toPoi", toPoi, true);
    }

    public Poi getToPoi() {
        return (Poi)readProperty("toPoi");
    }


}
