package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Device;

/**
 * Class _Log was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Log extends CayenneDataObject {

    public static final String LEVEL_PROPERTY = "level";
    public static final String LOG_TIME_PROPERTY = "logTime";
    public static final String MESSAGE_PROPERTY = "message";
    public static final String STACKTRACE_PROPERTY = "stacktrace";
    public static final String TAG_PROPERTY = "tag";
    public static final String TO_DEVICE_PROPERTY = "toDevice";

    public static final String ID_PK_COLUMN = "id";

    public void setLevel(String level) {
        writeProperty("level", level);
    }
    public String getLevel() {
        return (String)readProperty("level");
    }

    public void setLogTime(Date logTime) {
        writeProperty("logTime", logTime);
    }
    public Date getLogTime() {
        return (Date)readProperty("logTime");
    }

    public void setMessage(String message) {
        writeProperty("message", message);
    }
    public String getMessage() {
        return (String)readProperty("message");
    }

    public void setStacktrace(String stacktrace) {
        writeProperty("stacktrace", stacktrace);
    }
    public String getStacktrace() {
        return (String)readProperty("stacktrace");
    }

    public void setTag(String tag) {
        writeProperty("tag", tag);
    }
    public String getTag() {
        return (String)readProperty("tag");
    }

    public void setToDevice(Device toDevice) {
        setToOneTarget("toDevice", toDevice, true);
    }

    public Device getToDevice() {
        return (Device)readProperty("toDevice");
    }


}
