package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Geofence;
import at.fhv.itm14.fhvgis.persistence.cayenne.PoiType;
import at.fhv.itm14.fhvgis.persistence.cayenne.Segment;
import at.fhv.itm14.fhvgis.persistence.cayenne.Shedule;
import at.fhv.itm14.fhvgis.persistence.cayenne.Waypoint;

/**
 * Class _Poi was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Poi extends CayenneDataObject {

    public static final String EXT_REF_PROPERTY = "extRef";
    public static final String NAME_PROPERTY = "name";
    public static final String POSITION_PROPERTY = "position";
    public static final String RADIUS_PROPERTY = "radius";
    public static final String GEOFENCE_ARRAY_PROPERTY = "geofenceArray";
    public static final String SEGMENT_ARRAY_PROPERTY = "segmentArray";
    public static final String SEGMENT_ARRAY1_PROPERTY = "segmentArray1";
    public static final String SHEDULE_ARRAY_PROPERTY = "sheduleArray";
    public static final String TO_POI_TYPE_PROPERTY = "toPoiType";
    public static final String WAYPOINT_ARRAY_PROPERTY = "waypointArray";

    public static final String ID_PK_COLUMN = "id";

    public void setExtRef(String extRef) {
        writeProperty("extRef", extRef);
    }
    public String getExtRef() {
        return (String)readProperty("extRef");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPosition(String position) {
        writeProperty("position", position);
    }
    public String getPosition() {
        return (String)readProperty("position");
    }

    public void setRadius(Float radius) {
        writeProperty("radius", radius);
    }
    public Float getRadius() {
        return (Float)readProperty("radius");
    }

    public void addToGeofenceArray(Geofence obj) {
        addToManyTarget("geofenceArray", obj, true);
    }
    public void removeFromGeofenceArray(Geofence obj) {
        removeToManyTarget("geofenceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Geofence> getGeofenceArray() {
        return (List<Geofence>)readProperty("geofenceArray");
    }


    public void addToSegmentArray(Segment obj) {
        addToManyTarget("segmentArray", obj, true);
    }
    public void removeFromSegmentArray(Segment obj) {
        removeToManyTarget("segmentArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Segment> getSegmentArray() {
        return (List<Segment>)readProperty("segmentArray");
    }


    public void addToSegmentArray1(Segment obj) {
        addToManyTarget("segmentArray1", obj, true);
    }
    public void removeFromSegmentArray1(Segment obj) {
        removeToManyTarget("segmentArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Segment> getSegmentArray1() {
        return (List<Segment>)readProperty("segmentArray1");
    }


    public void addToSheduleArray(Shedule obj) {
        addToManyTarget("sheduleArray", obj, true);
    }
    public void removeFromSheduleArray(Shedule obj) {
        removeToManyTarget("sheduleArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Shedule> getSheduleArray() {
        return (List<Shedule>)readProperty("sheduleArray");
    }


    public void setToPoiType(PoiType toPoiType) {
        setToOneTarget("toPoiType", toPoiType, true);
    }

    public PoiType getToPoiType() {
        return (PoiType)readProperty("toPoiType");
    }


    public void addToWaypointArray(Waypoint obj) {
        addToManyTarget("waypointArray", obj, true);
    }
    public void removeFromWaypointArray(Waypoint obj) {
        removeToManyTarget("waypointArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Waypoint> getWaypointArray() {
        return (List<Waypoint>)readProperty("waypointArray");
    }


}
