package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Poi;

/**
 * Class _PoiType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PoiType extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String PRIVATE_PROPERTY = "private";
    public static final String POI_ARRAY_PROPERTY = "poiArray";

    public static final String ID_PK_COLUMN = "id";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPrivate(Boolean _private) {
        writeProperty("private", _private);
    }
    public Boolean getPrivate() {
        return (Boolean)readProperty("private");
    }

    public void addToPoiArray(Poi obj) {
        addToManyTarget("poiArray", obj, true);
    }
    public void removeFromPoiArray(Poi obj) {
        removeToManyTarget("poiArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Poi> getPoiArray() {
        return (List<Poi>)readProperty("poiArray");
    }


}
