package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _RasterColumns was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _RasterColumns extends CayenneDataObject {



}
