package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Poi;
import at.fhv.itm14.fhvgis.persistence.cayenne.Transportation;
import at.fhv.itm14.fhvgis.persistence.cayenne.TransportationRoute;
import at.fhv.itm14.fhvgis.persistence.cayenne.Waypoint;

/**
 * Class _Segment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Segment extends CayenneDataObject {

    public static final String TO_POI_PROPERTY = "toPoi";
    public static final String TO_POI1_PROPERTY = "toPoi1";
    public static final String TO_TRANSPORTATION_PROPERTY = "toTransportation";
    public static final String TO_TRANSPORTATION_ROUTE_PROPERTY = "toTransportationRoute";
    public static final String TO_WAYPOINT_PROPERTY = "toWaypoint";
    public static final String TO_WAYPOINT1_PROPERTY = "toWaypoint1";

    public static final String ID_PK_COLUMN = "id";

    public void setToPoi(Poi toPoi) {
        setToOneTarget("toPoi", toPoi, true);
    }

    public Poi getToPoi() {
        return (Poi)readProperty("toPoi");
    }


    public void setToPoi1(Poi toPoi1) {
        setToOneTarget("toPoi1", toPoi1, true);
    }

    public Poi getToPoi1() {
        return (Poi)readProperty("toPoi1");
    }


    public void setToTransportation(Transportation toTransportation) {
        setToOneTarget("toTransportation", toTransportation, true);
    }

    public Transportation getToTransportation() {
        return (Transportation)readProperty("toTransportation");
    }


    public void setToTransportationRoute(TransportationRoute toTransportationRoute) {
        setToOneTarget("toTransportationRoute", toTransportationRoute, true);
    }

    public TransportationRoute getToTransportationRoute() {
        return (TransportationRoute)readProperty("toTransportationRoute");
    }


    public void setToWaypoint(Waypoint toWaypoint) {
        setToOneTarget("toWaypoint", toWaypoint, true);
    }

    public Waypoint getToWaypoint() {
        return (Waypoint)readProperty("toWaypoint");
    }


    public void setToWaypoint1(Waypoint toWaypoint1) {
        setToOneTarget("toWaypoint1", toWaypoint1, true);
    }

    public Waypoint getToWaypoint1() {
        return (Waypoint)readProperty("toWaypoint1");
    }


}
