package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Shedule;

/**
 * Class _SheduleDay was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SheduleDay extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String SHEDULE_ARRAY_PROPERTY = "sheduleArray";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToSheduleArray(Shedule obj) {
        addToManyTarget("sheduleArray", obj, true);
    }
    public void removeFromSheduleArray(Shedule obj) {
        removeToManyTarget("sheduleArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Shedule> getSheduleArray() {
        return (List<Shedule>)readProperty("sheduleArray");
    }


}
