package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Poi;
import at.fhv.itm14.fhvgis.persistence.cayenne.SheduleDay;
import at.fhv.itm14.fhvgis.persistence.cayenne.TransportationRoute;

/**
 * Class _Shedule was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Shedule extends CayenneDataObject {

    public static final String ARRIVAL_TIME_PROPERTY = "arrivalTime";
    public static final String DEPARTURE_TIME_PROPERTY = "departureTime";
    public static final String EXPLICIT_DATE_PROPERTY = "explicitDate";
    public static final String SEQ_NO_PROPERTY = "seqNo";
    public static final String TRIP_NR_PROPERTY = "tripNr";
    public static final String VALID_FROM_PROPERTY = "validFrom";
    public static final String VALID_UNTIL_PROPERTY = "validUntil";
    public static final String TO_POI_PROPERTY = "toPoi";
    public static final String TO_SHEDULE_DAY_PROPERTY = "toSheduleDay";
    public static final String TO_TRANSPORTATION_ROUTE_PROPERTY = "toTransportationRoute";

    public static final String ID_PK_COLUMN = "id";

    public void setArrivalTime(Date arrivalTime) {
        writeProperty("arrivalTime", arrivalTime);
    }
    public Date getArrivalTime() {
        return (Date)readProperty("arrivalTime");
    }

    public void setDepartureTime(Date departureTime) {
        writeProperty("departureTime", departureTime);
    }
    public Date getDepartureTime() {
        return (Date)readProperty("departureTime");
    }

    public void setExplicitDate(Date explicitDate) {
        writeProperty("explicitDate", explicitDate);
    }
    public Date getExplicitDate() {
        return (Date)readProperty("explicitDate");
    }

    public void setSeqNo(Integer seqNo) {
        writeProperty("seqNo", seqNo);
    }
    public Integer getSeqNo() {
        return (Integer)readProperty("seqNo");
    }

    public void setTripNr(Integer tripNr) {
        writeProperty("tripNr", tripNr);
    }
    public Integer getTripNr() {
        return (Integer)readProperty("tripNr");
    }

    public void setValidFrom(Date validFrom) {
        writeProperty("validFrom", validFrom);
    }
    public Date getValidFrom() {
        return (Date)readProperty("validFrom");
    }

    public void setValidUntil(Date validUntil) {
        writeProperty("validUntil", validUntil);
    }
    public Date getValidUntil() {
        return (Date)readProperty("validUntil");
    }

    public void setToPoi(Poi toPoi) {
        setToOneTarget("toPoi", toPoi, true);
    }

    public Poi getToPoi() {
        return (Poi)readProperty("toPoi");
    }


    public void setToSheduleDay(SheduleDay toSheduleDay) {
        setToOneTarget("toSheduleDay", toSheduleDay, true);
    }

    public SheduleDay getToSheduleDay() {
        return (SheduleDay)readProperty("toSheduleDay");
    }


    public void setToTransportationRoute(TransportationRoute toTransportationRoute) {
        setToOneTarget("toTransportationRoute", toTransportationRoute, true);
    }

    public TransportationRoute getToTransportationRoute() {
        return (TransportationRoute)readProperty("toTransportationRoute");
    }


}
