package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _SpatialRefSys was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpatialRefSys extends CayenneDataObject {

    public static final String AUTH_NAME_PROPERTY = "authName";
    public static final String AUTH_SRID_PROPERTY = "authSrid";
    public static final String PROJ4TEXT_PROPERTY = "proj4text";
    public static final String SRTEXT_PROPERTY = "srtext";

    public static final String SRID_PK_COLUMN = "srid";

    public void setAuthName(String authName) {
        writeProperty("authName", authName);
    }
    public String getAuthName() {
        return (String)readProperty("authName");
    }

    public void setAuthSrid(Integer authSrid) {
        writeProperty("authSrid", authSrid);
    }
    public Integer getAuthSrid() {
        return (Integer)readProperty("authSrid");
    }

    public void setProj4text(String proj4text) {
        writeProperty("proj4text", proj4text);
    }
    public String getProj4text() {
        return (String)readProperty("proj4text");
    }

    public void setSrtext(String srtext) {
        writeProperty("srtext", srtext);
    }
    public String getSrtext() {
        return (String)readProperty("srtext");
    }

}
