package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Segment;
import at.fhv.itm14.fhvgis.persistence.cayenne.TransportationRoute;
import at.fhv.itm14.fhvgis.persistence.cayenne.Waypoint;

/**
 * Class _Transportation was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Transportation extends CayenneDataObject {

    public static final String AVARAGE_SPEED_PROPERTY = "avarageSpeed";
    public static final String COLOR_PROPERTY = "color";
    public static final String MAX_SPEED_PROPERTY = "maxSpeed";
    public static final String NAME_PROPERTY = "name";
    public static final String SEGMENT_ARRAY_PROPERTY = "segmentArray";
    public static final String TRANSPORTATION_ROUTE_ARRAY_PROPERTY = "transportationRouteArray";
    public static final String WAYPOINT_ARRAY_PROPERTY = "waypointArray";

    public static final String ID_PK_COLUMN = "id";

    public void setAvarageSpeed(Float avarageSpeed) {
        writeProperty("avarageSpeed", avarageSpeed);
    }
    public Float getAvarageSpeed() {
        return (Float)readProperty("avarageSpeed");
    }

    public void setColor(String color) {
        writeProperty("color", color);
    }
    public String getColor() {
        return (String)readProperty("color");
    }

    public void setMaxSpeed(Float maxSpeed) {
        writeProperty("maxSpeed", maxSpeed);
    }
    public Float getMaxSpeed() {
        return (Float)readProperty("maxSpeed");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToSegmentArray(Segment obj) {
        addToManyTarget("segmentArray", obj, true);
    }
    public void removeFromSegmentArray(Segment obj) {
        removeToManyTarget("segmentArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Segment> getSegmentArray() {
        return (List<Segment>)readProperty("segmentArray");
    }


    public void addToTransportationRouteArray(TransportationRoute obj) {
        addToManyTarget("transportationRouteArray", obj, true);
    }
    public void removeFromTransportationRouteArray(TransportationRoute obj) {
        removeToManyTarget("transportationRouteArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TransportationRoute> getTransportationRouteArray() {
        return (List<TransportationRoute>)readProperty("transportationRouteArray");
    }


    public void addToWaypointArray(Waypoint obj) {
        addToManyTarget("waypointArray", obj, true);
    }
    public void removeFromWaypointArray(Waypoint obj) {
        removeToManyTarget("waypointArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Waypoint> getWaypointArray() {
        return (List<Waypoint>)readProperty("waypointArray");
    }


}
