package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Segment;
import at.fhv.itm14.fhvgis.persistence.cayenne.Shedule;
import at.fhv.itm14.fhvgis.persistence.cayenne.Transportation;
import at.fhv.itm14.fhvgis.persistence.cayenne.Waypoint;

/**
 * Class _TransportationRoute was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TransportationRoute extends CayenneDataObject {

    public static final String DESC_PROPERTY = "desc";
    public static final String DESC_FROM_PROPERTY = "descFrom";
    public static final String DESC_TO_PROPERTY = "descTo";
    public static final String EXT_REF_PROPERTY = "extRef";
    public static final String NAME_PROPERTY = "name";
    public static final String NETWORK_PROPERTY = "network";
    public static final String OPERATOR_PROPERTY = "operator";
    public static final String ROUTE_NO_PROPERTY = "routeNo";
    public static final String VALID_FROM_PROPERTY = "validFrom";
    public static final String VALID_UNTIL_PROPERTY = "validUntil";
    public static final String SEGMENT_ARRAY_PROPERTY = "segmentArray";
    public static final String SHEDULE_ARRAY_PROPERTY = "sheduleArray";
    public static final String TO_TRANSPORTATION_PROPERTY = "toTransportation";
    public static final String WAYPOINT_ARRAY_PROPERTY = "waypointArray";

    public static final String ID_PK_COLUMN = "id";

    public void setDesc(String desc) {
        writeProperty("desc", desc);
    }
    public String getDesc() {
        return (String)readProperty("desc");
    }

    public void setDescFrom(String descFrom) {
        writeProperty("descFrom", descFrom);
    }
    public String getDescFrom() {
        return (String)readProperty("descFrom");
    }

    public void setDescTo(String descTo) {
        writeProperty("descTo", descTo);
    }
    public String getDescTo() {
        return (String)readProperty("descTo");
    }

    public void setExtRef(String extRef) {
        writeProperty("extRef", extRef);
    }
    public String getExtRef() {
        return (String)readProperty("extRef");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setNetwork(String network) {
        writeProperty("network", network);
    }
    public String getNetwork() {
        return (String)readProperty("network");
    }

    public void setOperator(String operator) {
        writeProperty("operator", operator);
    }
    public String getOperator() {
        return (String)readProperty("operator");
    }

    public void setRouteNo(String routeNo) {
        writeProperty("routeNo", routeNo);
    }
    public String getRouteNo() {
        return (String)readProperty("routeNo");
    }

    public void setValidFrom(Date validFrom) {
        writeProperty("validFrom", validFrom);
    }
    public Date getValidFrom() {
        return (Date)readProperty("validFrom");
    }

    public void setValidUntil(Date validUntil) {
        writeProperty("validUntil", validUntil);
    }
    public Date getValidUntil() {
        return (Date)readProperty("validUntil");
    }

    public void addToSegmentArray(Segment obj) {
        addToManyTarget("segmentArray", obj, true);
    }
    public void removeFromSegmentArray(Segment obj) {
        removeToManyTarget("segmentArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Segment> getSegmentArray() {
        return (List<Segment>)readProperty("segmentArray");
    }


    public void addToSheduleArray(Shedule obj) {
        addToManyTarget("sheduleArray", obj, true);
    }
    public void removeFromSheduleArray(Shedule obj) {
        removeToManyTarget("sheduleArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Shedule> getSheduleArray() {
        return (List<Shedule>)readProperty("sheduleArray");
    }


    public void setToTransportation(Transportation toTransportation) {
        setToOneTarget("toTransportation", toTransportation, true);
    }

    public Transportation getToTransportation() {
        return (Transportation)readProperty("toTransportation");
    }


    public void addToWaypointArray(Waypoint obj) {
        addToManyTarget("waypointArray", obj, true);
    }
    public void removeFromWaypointArray(Waypoint obj) {
        removeToManyTarget("waypointArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Waypoint> getWaypointArray() {
        return (List<Waypoint>)readProperty("waypointArray");
    }


}
