package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Device;

/**
 * Class _Track was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Track extends CayenneDataObject {

    public static final String END_PROPERTY = "end";
    public static final String START_PROPERTY = "start";
    public static final String TO_DEVICE_PROPERTY = "toDevice";

    public static final String ID_PK_COLUMN = "id";

    public void setEnd(Date end) {
        writeProperty("end", end);
    }
    public Date getEnd() {
        return (Date)readProperty("end");
    }

    public void setStart(Date start) {
        writeProperty("start", start);
    }
    public Date getStart() {
        return (Date)readProperty("start");
    }

    public void setToDevice(Device toDevice) {
        setToOneTarget("toDevice", toDevice, true);
    }

    public Device getToDevice() {
        return (Device)readProperty("toDevice");
    }


}
