package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Device;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String PASSWORD_PROPERTY = "password";
    public static final String USERNAME_PROPERTY = "username";
    public static final String DEVICE_ARRAY_PROPERTY = "deviceArray";

    public static final String ID_PK_COLUMN = "id";

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setUsername(String username) {
        writeProperty("username", username);
    }
    public String getUsername() {
        return (String)readProperty("username");
    }

    public void addToDeviceArray(Device obj) {
        addToManyTarget("deviceArray", obj, true);
    }
    public void removeFromDeviceArray(Device obj) {
        removeToManyTarget("deviceArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Device> getDeviceArray() {
        return (List<Device>)readProperty("deviceArray");
    }


}
