package at.fhv.itm14.fhvgis.persistence.cayenne.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import at.fhv.itm14.fhvgis.persistence.cayenne.Poi;
import at.fhv.itm14.fhvgis.persistence.cayenne.Segment;
import at.fhv.itm14.fhvgis.persistence.cayenne.Transportation;
import at.fhv.itm14.fhvgis.persistence.cayenne.TransportationRoute;

/**
 * Class _Waypoint was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Waypoint extends CayenneDataObject {

    public static final String ACCURACY_PROPERTY = "accuracy";
    public static final String NR_OF_SATELLITES_PROPERTY = "nrOfSatellites";
    public static final String POSITION_PROPERTY = "position";
    public static final String RECORD_TIME_PROPERTY = "recordTime";
    public static final String SPEED_PROPERTY = "speed";
    public static final String VALID_PROPERTY = "valid";
    public static final String SEGMENT_ARRAY_PROPERTY = "segmentArray";
    public static final String SEGMENT_ARRAY1_PROPERTY = "segmentArray1";
    public static final String TO_POI_PROPERTY = "toPoi";
    public static final String TO_TRANSPORTATION_PROPERTY = "toTransportation";
    public static final String TO_TRANSPORTATION_ROUTE_PROPERTY = "toTransportationRoute";

    public static final String ID_PK_COLUMN = "id";

    public void setAccuracy(Double accuracy) {
        writeProperty("accuracy", accuracy);
    }
    public Double getAccuracy() {
        return (Double)readProperty("accuracy");
    }

    public void setNrOfSatellites(Integer nrOfSatellites) {
        writeProperty("nrOfSatellites", nrOfSatellites);
    }
    public Integer getNrOfSatellites() {
        return (Integer)readProperty("nrOfSatellites");
    }

    public void setPosition(String position) {
        writeProperty("position", position);
    }
    public String getPosition() {
        return (String)readProperty("position");
    }

    public void setRecordTime(Date recordTime) {
        writeProperty("recordTime", recordTime);
    }
    public Date getRecordTime() {
        return (Date)readProperty("recordTime");
    }

    public void setSpeed(Float speed) {
        writeProperty("speed", speed);
    }
    public Float getSpeed() {
        return (Float)readProperty("speed");
    }

    public void setValid(Boolean valid) {
        writeProperty("valid", valid);
    }
    public Boolean getValid() {
        return (Boolean)readProperty("valid");
    }

    public void addToSegmentArray(Segment obj) {
        addToManyTarget("segmentArray", obj, true);
    }
    public void removeFromSegmentArray(Segment obj) {
        removeToManyTarget("segmentArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Segment> getSegmentArray() {
        return (List<Segment>)readProperty("segmentArray");
    }


    public void addToSegmentArray1(Segment obj) {
        addToManyTarget("segmentArray1", obj, true);
    }
    public void removeFromSegmentArray1(Segment obj) {
        removeToManyTarget("segmentArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Segment> getSegmentArray1() {
        return (List<Segment>)readProperty("segmentArray1");
    }


    public void setToPoi(Poi toPoi) {
        setToOneTarget("toPoi", toPoi, true);
    }

    public Poi getToPoi() {
        return (Poi)readProperty("toPoi");
    }


    public void setToTransportation(Transportation toTransportation) {
        setToOneTarget("toTransportation", toTransportation, true);
    }

    public Transportation getToTransportation() {
        return (Transportation)readProperty("toTransportation");
    }


    public void setToTransportationRoute(TransportationRoute toTransportationRoute) {
        setToOneTarget("toTransportationRoute", toTransportationRoute, true);
    }

    public TransportationRoute getToTransportationRoute() {
        return (TransportationRoute)readProperty("toTransportationRoute");
    }


}
