package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Geofence generated by hbm2java
 */
public class Geofence implements java.io.Serializable {

	private Serializable id;
	private Poi poi;
	private float radius;
	private Set<GpsPosition> gpsPositions = new HashSet<GpsPosition>(0);

	public Geofence() {
	}

	public Geofence(Serializable id, Poi poi, float radius) {
		this.id = id;
		this.poi = poi;
		this.radius = radius;
	}

	public Geofence(Serializable id, Poi poi, float radius, Set<GpsPosition> gpsPositions) {
		this.id = id;
		this.poi = poi;
		this.radius = radius;
		this.gpsPositions = gpsPositions;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public Poi getPoi() {
		return this.poi;
	}

	public void setPoi(Poi poi) {
		this.poi = poi;
	}

	public float getRadius() {
		return this.radius;
	}

	public void setRadius(float radius) {
		this.radius = radius;
	}

	public Set<GpsPosition> getGpsPositions() {
		return this.gpsPositions;
	}

	public void setGpsPositions(Set<GpsPosition> gpsPositions) {
		this.gpsPositions = gpsPositions;
	}

}
