package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 28.10.2015 12:44:52 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Geofence generated by hbm2java
 */
@Entity
@Table(name = "geofence", schema = "public")
public class Geofence implements java.io.Serializable {

	private String id;
	private Poi poi;
	private float radius;
	private Set<GpsPosition> gpsPositions = new HashSet<GpsPosition>(0);

	public Geofence() {
	}

	public Geofence(String id, Poi poi, float radius) {
		this.id = id;
		this.poi = poi;
		this.radius = radius;
	}

	public Geofence(String id, Poi poi, float radius, Set<GpsPosition> gpsPositions) {
		this.id = id;
		this.poi = poi;
		this.radius = radius;
		this.gpsPositions = gpsPositions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poi_id", nullable = false)
	public Poi getPoi() {
		return this.poi;
	}

	public void setPoi(Poi poi) {
		this.poi = poi;
	}

	@Column(name = "radius", nullable = false, precision = 8, scale = 8)
	public float getRadius() {
		return this.radius;
	}

	public void setRadius(float radius) {
		this.radius = radius;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "geofence")
	public Set<GpsPosition> getGpsPositions() {
		return this.gpsPositions;
	}

	public void setGpsPositions(Set<GpsPosition> gpsPositions) {
		this.gpsPositions = gpsPositions;
	}

}
