package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 28.10.2015 12:44:52 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GpsPosition generated by hbm2java
 */
@Entity
@Table(name = "gps_position", schema = "public")
public class GpsPosition implements java.io.Serializable {

	private String id;
	private Geofence geofence;
	private String position;
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);

	public GpsPosition() {
	}

	public GpsPosition(String id, String position) {
		this.id = id;
		this.position = position;
	}

	public GpsPosition(String id, Geofence geofence, String position, Set<Waypoint> waypoints) {
		this.id = id;
		this.geofence = geofence;
		this.position = position;
		this.waypoints = waypoints;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "geofence_id")
	public Geofence getGeofence() {
		return this.geofence;
	}

	public void setGeofence(Geofence geofence) {
		this.geofence = geofence;
	}

	@Column(name = "position", nullable = false)
	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gpsPosition")
	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

}
