package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * GpsPosition generated by hbm2java
 */
public class GpsPosition implements java.io.Serializable {

	private Serializable id;
	private Geofence geofence;
	private Serializable position;
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);

	public GpsPosition() {
	}

	public GpsPosition(Serializable id, Serializable position) {
		this.id = id;
		this.position = position;
	}

	public GpsPosition(Serializable id, Geofence geofence, Serializable position, Set<Waypoint> waypoints) {
		this.id = id;
		this.geofence = geofence;
		this.position = position;
		this.waypoints = waypoints;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public Geofence getGeofence() {
		return this.geofence;
	}

	public void setGeofence(Geofence geofence) {
		this.geofence = geofence;
	}

	public Serializable getPosition() {
		return this.position;
	}

	public void setPosition(Serializable position) {
		this.position = position;
	}

	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

}
