package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

/**
 * Layer generated by hbm2java
 */
public class Layer implements java.io.Serializable {

	private LayerId id;
	private Topology topology;
	private String schemaName;
	private String tableName;
	private String featureColumn;
	private int featureType;
	private int level;
	private Integer childId;

	public Layer() {
	}

	public Layer(LayerId id, Topology topology, String schemaName, String tableName, String featureColumn,
			int featureType, int level) {
		this.id = id;
		this.topology = topology;
		this.schemaName = schemaName;
		this.tableName = tableName;
		this.featureColumn = featureColumn;
		this.featureType = featureType;
		this.level = level;
	}

	public Layer(LayerId id, Topology topology, String schemaName, String tableName, String featureColumn,
			int featureType, int level, Integer childId) {
		this.id = id;
		this.topology = topology;
		this.schemaName = schemaName;
		this.tableName = tableName;
		this.featureColumn = featureColumn;
		this.featureType = featureType;
		this.level = level;
		this.childId = childId;
	}

	public LayerId getId() {
		return this.id;
	}

	public void setId(LayerId id) {
		this.id = id;
	}

	public Topology getTopology() {
		return this.topology;
	}

	public void setTopology(Topology topology) {
		this.topology = topology;
	}

	public String getSchemaName() {
		return this.schemaName;
	}

	public void setSchemaName(String schemaName) {
		this.schemaName = schemaName;
	}

	public String getTableName() {
		return this.tableName;
	}

	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	public String getFeatureColumn() {
		return this.featureColumn;
	}

	public void setFeatureColumn(String featureColumn) {
		this.featureColumn = featureColumn;
	}

	public int getFeatureType() {
		return this.featureType;
	}

	public void setFeatureType(int featureType) {
		this.featureType = featureType;
	}

	public int getLevel() {
		return this.level;
	}

	public void setLevel(int level) {
		this.level = level;
	}

	public Integer getChildId() {
		return this.childId;
	}

	public void setChildId(Integer childId) {
		this.childId = childId;
	}

}
