package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 28.10.2015 12:44:52 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Poi generated by hbm2java
 */
@Entity
@Table(name = "poi", schema = "public")
public class Poi implements java.io.Serializable {

	private String id;
	private PoiType poiType;
	private String name;
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);
	private Set<Geofence> geofences = new HashSet<Geofence>(0);
	private Set<Segment> segmentsForPoiFromId = new HashSet<Segment>(0);
	private Set<Segment> segmentsForPoiToId = new HashSet<Segment>(0);

	public Poi() {
	}

	public Poi(String id, PoiType poiType) {
		this.id = id;
		this.poiType = poiType;
	}

	public Poi(String id, PoiType poiType, String name, Set<Waypoint> waypoints, Set<Geofence> geofences,
			Set<Segment> segmentsForPoiFromId, Set<Segment> segmentsForPoiToId) {
		this.id = id;
		this.poiType = poiType;
		this.name = name;
		this.waypoints = waypoints;
		this.geofences = geofences;
		this.segmentsForPoiFromId = segmentsForPoiFromId;
		this.segmentsForPoiToId = segmentsForPoiToId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poi_type_id", nullable = false)
	public PoiType getPoiType() {
		return this.poiType;
	}

	public void setPoiType(PoiType poiType) {
		this.poiType = poiType;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poi")
	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poi")
	public Set<Geofence> getGeofences() {
		return this.geofences;
	}

	public void setGeofences(Set<Geofence> geofences) {
		this.geofences = geofences;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poiByPoiFromId")
	public Set<Segment> getSegmentsForPoiFromId() {
		return this.segmentsForPoiFromId;
	}

	public void setSegmentsForPoiFromId(Set<Segment> segmentsForPoiFromId) {
		this.segmentsForPoiFromId = segmentsForPoiFromId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poiByPoiToId")
	public Set<Segment> getSegmentsForPoiToId() {
		return this.segmentsForPoiToId;
	}

	public void setSegmentsForPoiToId(Set<Segment> segmentsForPoiToId) {
		this.segmentsForPoiToId = segmentsForPoiToId;
	}

}
