package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Poi generated by hbm2java
 */
public class Poi implements java.io.Serializable {

	private Serializable id;
	private PoiType poiType;
	private String name;
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);
	private Set<Geofence> geofences = new HashSet<Geofence>(0);
	private Set<Segment> segmentsForPoiFromId = new HashSet<Segment>(0);
	private Set<Segment> segmentsForPoiToId = new HashSet<Segment>(0);

	public Poi() {
	}

	public Poi(Serializable id, PoiType poiType) {
		this.id = id;
		this.poiType = poiType;
	}

	public Poi(Serializable id, PoiType poiType, String name, Set<Waypoint> waypoints, Set<Geofence> geofences,
			Set<Segment> segmentsForPoiFromId, Set<Segment> segmentsForPoiToId) {
		this.id = id;
		this.poiType = poiType;
		this.name = name;
		this.waypoints = waypoints;
		this.geofences = geofences;
		this.segmentsForPoiFromId = segmentsForPoiFromId;
		this.segmentsForPoiToId = segmentsForPoiToId;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public PoiType getPoiType() {
		return this.poiType;
	}

	public void setPoiType(PoiType poiType) {
		this.poiType = poiType;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

	public Set<Geofence> getGeofences() {
		return this.geofences;
	}

	public void setGeofences(Set<Geofence> geofences) {
		this.geofences = geofences;
	}

	public Set<Segment> getSegmentsForPoiFromId() {
		return this.segmentsForPoiFromId;
	}

	public void setSegmentsForPoiFromId(Set<Segment> segmentsForPoiFromId) {
		this.segmentsForPoiFromId = segmentsForPoiFromId;
	}

	public Set<Segment> getSegmentsForPoiToId() {
		return this.segmentsForPoiToId;
	}

	public void setSegmentsForPoiToId(Set<Segment> segmentsForPoiToId) {
		this.segmentsForPoiToId = segmentsForPoiToId;
	}

}
