package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 17.11.2015 09:21:54 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.type.UUIDBinaryType;

import com.vividsolutions.jts.geom.Geometry;

/**
 * Poi generated by hbm2java
 */
@Entity
@Table(name = "poi", schema = "public")
public class Poi implements java.io.Serializable {

	private UUID id;
	private PoiType poiType;
	private String name;
	private Float radius;
	private String extRef;
	private Geometry position;
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);
	private Set<Geofence> geofences = new HashSet<Geofence>(0);
	private Set<Segment> segmentsForPoiFromId = new HashSet<Segment>(0);
	private Set<Shedule> shedules = new HashSet<Shedule>(0);
	private Set<Segment> segmentsForPoiToId = new HashSet<Segment>(0);

	public Poi() {
	}

	public Poi(UUID id, PoiType poiType, Geometry position) {
		this.id = id;
		this.poiType = poiType;
		this.position = position;
	}

	public Poi(UUID id, PoiType poiType, String name, Float radius, String extRef, Geometry position,
			Set<Waypoint> waypoints, Set<Geofence> geofences, Set<Segment> segmentsForPoiFromId, Set<Shedule> shedules,
			Set<Segment> segmentsForPoiToId) {
		this.id = id;
		this.poiType = poiType;
		this.name = name;
		this.radius = radius;
		this.extRef = extRef;
		this.position = position;
		this.waypoints = waypoints;
		this.geofences = geofences;
		this.segmentsForPoiFromId = segmentsForPoiFromId;
		this.shedules = shedules;
		this.segmentsForPoiToId = segmentsForPoiToId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poi_type_id", nullable = false)
	public PoiType getPoiType() {
		return this.poiType;
	}

	public void setPoiType(PoiType poiType) {
		this.poiType = poiType;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "radius", precision = 8, scale = 8)
	public Float getRadius() {
		return this.radius;
	}

	public void setRadius(Float radius) {
		this.radius = radius;
	}

	@Column(name = "ext_ref")
	public String getExtRef() {
		return this.extRef;
	}

	public void setExtRef(String extRef) {
		this.extRef = extRef;
	}

	@Column(name = "position", nullable = false)
	public Geometry getPosition() {
		return this.position;
	}

	public void setPosition(Geometry position) {
		this.position = position;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poi")
	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poi")
	public Set<Geofence> getGeofences() {
		return this.geofences;
	}

	public void setGeofences(Set<Geofence> geofences) {
		this.geofences = geofences;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poiByPoiFromId")
	public Set<Segment> getSegmentsForPoiFromId() {
		return this.segmentsForPoiFromId;
	}

	public void setSegmentsForPoiFromId(Set<Segment> segmentsForPoiFromId) {
		this.segmentsForPoiFromId = segmentsForPoiFromId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poi")
	public Set<Shedule> getShedules() {
		return this.shedules;
	}

	public void setShedules(Set<Shedule> shedules) {
		this.shedules = shedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poiByPoiToId")
	public Set<Segment> getSegmentsForPoiToId() {
		return this.segmentsForPoiToId;
	}

	public void setSegmentsForPoiToId(Set<Segment> segmentsForPoiToId) {
		this.segmentsForPoiToId = segmentsForPoiToId;
	}

}
