package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 17.11.2015 09:21:54 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PoiType generated by hbm2java
 */
@Entity
@Table(name = "poi_type", schema = "public")
public class PoiType implements java.io.Serializable {

	private UUID id;
	private String name;
	private boolean private_;
	private Set<Poi> pois = new HashSet<Poi>(0);

	public PoiType() {
	}

	public PoiType(UUID id, boolean private_) {
		this.id = id;
		this.private_ = private_;
	}

	public PoiType(UUID id, String name, boolean private_, Set<Poi> pois) {
		this.id = id;
		this.name = name;
		this.private_ = private_;
		this.pois = pois;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "private", nullable = false)
	public boolean isPrivate_() {
		return this.private_;
	}

	public void setPrivate_(boolean private_) {
		this.private_ = private_;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "poiType")
	public Set<Poi> getPois() {
		return this.pois;
	}

	public void setPois(Set<Poi> pois) {
		this.pois = pois;
	}

}
