package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * PoiType generated by hbm2java
 */
public class PoiType implements java.io.Serializable {

	private Serializable id;
	private String name;
	private boolean private_;
	private Set<Poi> pois = new HashSet<Poi>(0);

	public PoiType() {
	}

	public PoiType(Serializable id, boolean private_) {
		this.id = id;
		this.private_ = private_;
	}

	public PoiType(Serializable id, String name, boolean private_, Set<Poi> pois) {
		this.id = id;
		this.name = name;
		this.private_ = private_;
		this.pois = pois;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isPrivate_() {
		return this.private_;
	}

	public void setPrivate_(boolean private_) {
		this.private_ = private_;
	}

	public Set<Poi> getPois() {
		return this.pois;
	}

	public void setPois(Set<Poi> pois) {
		this.pois = pois;
	}

}
