package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Segment generated by hbm2java
 */
public class Segment implements java.io.Serializable {

	private Serializable id;
	private TransportationRoute transportationRoute;
	private Poi poiByPoiToId;
	private Transportation transportation;
	private Waypoint waypointByWaypointFromId;
	private Poi poiByPoiFromId;
	private Waypoint waypointByWaypointToId;

	public Segment() {
	}

	public Segment(Serializable id, Transportation transportation, Waypoint waypointByWaypointFromId,
			Waypoint waypointByWaypointToId) {
		this.id = id;
		this.transportation = transportation;
		this.waypointByWaypointFromId = waypointByWaypointFromId;
		this.waypointByWaypointToId = waypointByWaypointToId;
	}

	public Segment(Serializable id, TransportationRoute transportationRoute, Poi poiByPoiToId,
			Transportation transportation, Waypoint waypointByWaypointFromId, Poi poiByPoiFromId,
			Waypoint waypointByWaypointToId) {
		this.id = id;
		this.transportationRoute = transportationRoute;
		this.poiByPoiToId = poiByPoiToId;
		this.transportation = transportation;
		this.waypointByWaypointFromId = waypointByWaypointFromId;
		this.poiByPoiFromId = poiByPoiFromId;
		this.waypointByWaypointToId = waypointByWaypointToId;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public TransportationRoute getTransportationRoute() {
		return this.transportationRoute;
	}

	public void setTransportationRoute(TransportationRoute transportationRoute) {
		this.transportationRoute = transportationRoute;
	}

	public Poi getPoiByPoiToId() {
		return this.poiByPoiToId;
	}

	public void setPoiByPoiToId(Poi poiByPoiToId) {
		this.poiByPoiToId = poiByPoiToId;
	}

	public Transportation getTransportation() {
		return this.transportation;
	}

	public void setTransportation(Transportation transportation) {
		this.transportation = transportation;
	}

	public Waypoint getWaypointByWaypointFromId() {
		return this.waypointByWaypointFromId;
	}

	public void setWaypointByWaypointFromId(Waypoint waypointByWaypointFromId) {
		this.waypointByWaypointFromId = waypointByWaypointFromId;
	}

	public Poi getPoiByPoiFromId() {
		return this.poiByPoiFromId;
	}

	public void setPoiByPoiFromId(Poi poiByPoiFromId) {
		this.poiByPoiFromId = poiByPoiFromId;
	}

	public Waypoint getWaypointByWaypointToId() {
		return this.waypointByWaypointToId;
	}

	public void setWaypointByWaypointToId(Waypoint waypointByWaypointToId) {
		this.waypointByWaypointToId = waypointByWaypointToId;
	}

}
