package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * SheduleDay generated by hbm2java
 */
public class SheduleDay implements java.io.Serializable {

	private Serializable id;
	private String name;
	private String description;
	private Set<Shedule> shedules = new HashSet<Shedule>(0);

	public SheduleDay() {
	}

	public SheduleDay(Serializable id) {
		this.id = id;
	}

	public SheduleDay(Serializable id, String name, String description, Set<Shedule> shedules) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.shedules = shedules;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Shedule> getShedules() {
		return this.shedules;
	}

	public void setShedules(Set<Shedule> shedules) {
		this.shedules = shedules;
	}

}
