package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Shedule generated by hbm2java
 */
public class Shedule implements java.io.Serializable {

	private Serializable id;
	private TransportationRoute transportationRoute;
	private Shedule shedule;
	private SheduleDay sheduleDay;
	private int tripNr;
	private Date validFrom;
	private Date validUntil;
	private Date explicitDate;
	private Date arrivalTime;
	private Date departureTime;
	private Set<Shedule> shedules = new HashSet<Shedule>(0);

	public Shedule() {
	}

	public Shedule(Serializable id, TransportationRoute transportationRoute, Shedule shedule, SheduleDay sheduleDay,
			int tripNr, Date arrivalTime) {
		this.id = id;
		this.transportationRoute = transportationRoute;
		this.shedule = shedule;
		this.sheduleDay = sheduleDay;
		this.tripNr = tripNr;
		this.arrivalTime = arrivalTime;
	}

	public Shedule(Serializable id, TransportationRoute transportationRoute, Shedule shedule, SheduleDay sheduleDay,
			int tripNr, Date validFrom, Date validUntil, Date explicitDate, Date arrivalTime, Date departureTime,
			Set<Shedule> shedules) {
		this.id = id;
		this.transportationRoute = transportationRoute;
		this.shedule = shedule;
		this.sheduleDay = sheduleDay;
		this.tripNr = tripNr;
		this.validFrom = validFrom;
		this.validUntil = validUntil;
		this.explicitDate = explicitDate;
		this.arrivalTime = arrivalTime;
		this.departureTime = departureTime;
		this.shedules = shedules;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public TransportationRoute getTransportationRoute() {
		return this.transportationRoute;
	}

	public void setTransportationRoute(TransportationRoute transportationRoute) {
		this.transportationRoute = transportationRoute;
	}

	public Shedule getShedule() {
		return this.shedule;
	}

	public void setShedule(Shedule shedule) {
		this.shedule = shedule;
	}

	public SheduleDay getSheduleDay() {
		return this.sheduleDay;
	}

	public void setSheduleDay(SheduleDay sheduleDay) {
		this.sheduleDay = sheduleDay;
	}

	public int getTripNr() {
		return this.tripNr;
	}

	public void setTripNr(int tripNr) {
		this.tripNr = tripNr;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidUntil() {
		return this.validUntil;
	}

	public void setValidUntil(Date validUntil) {
		this.validUntil = validUntil;
	}

	public Date getExplicitDate() {
		return this.explicitDate;
	}

	public void setExplicitDate(Date explicitDate) {
		this.explicitDate = explicitDate;
	}

	public Date getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Date arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	public Date getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(Date departureTime) {
		this.departureTime = departureTime;
	}

	public Set<Shedule> getShedules() {
		return this.shedules;
	}

	public void setShedules(Set<Shedule> shedules) {
		this.shedules = shedules;
	}

}
