package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 28.10.2015 12:44:52 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SheduleDay generated by hbm2java
 */
@Entity
@Table(name = "shedule_day", schema = "public")
public class SheduleDay implements java.io.Serializable {

	private String id;
	private String name;
	private String description;
	private Set<Shedule> shedules = new HashSet<Shedule>(0);

	public SheduleDay() {
	}

	public SheduleDay(String id) {
		this.id = id;
	}

	public SheduleDay(String id, String name, String description, Set<Shedule> shedules) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.shedules = shedules;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sheduleDay")
	public Set<Shedule> getShedules() {
		return this.shedules;
	}

	public void setShedules(Set<Shedule> shedules) {
		this.shedules = shedules;
	}

}
