package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 17.11.2015 09:21:54 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.type.UUIDBinaryType;

/**
 * SheduleDay generated by hbm2java
 */
@Entity
@Table(name = "shedule_day", schema = "public")
public class SheduleDay implements java.io.Serializable {

	private UUID id;
	private String name;
	private String description;
	private Set<Shedule> shedules = new HashSet<Shedule>(0);

	public SheduleDay() {
	}

	public SheduleDay(UUID id) {
		this.id = id;
	}

	public SheduleDay(UUID id, String name, String description, Set<Shedule> shedules) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.shedules = shedules;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sheduleDay")
	public Set<Shedule> getShedules() {
		return this.shedules;
	}

	public void setShedules(Set<Shedule> shedules) {
		this.shedules = shedules;
	}

}
