package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Topology generated by hbm2java
 */
public class Topology implements java.io.Serializable {

	private int id;
	private String name;
	private int srid;
	private double precision;
	private boolean hasz;
	private Set<Layer> layers = new HashSet<Layer>(0);

	public Topology() {
	}

	public Topology(int id, String name, int srid, double precision, boolean hasz) {
		this.id = id;
		this.name = name;
		this.srid = srid;
		this.precision = precision;
		this.hasz = hasz;
	}

	public Topology(int id, String name, int srid, double precision, boolean hasz, Set<Layer> layers) {
		this.id = id;
		this.name = name;
		this.srid = srid;
		this.precision = precision;
		this.hasz = hasz;
		this.layers = layers;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public int getSrid() {
		return this.srid;
	}

	public void setSrid(int srid) {
		this.srid = srid;
	}

	public double getPrecision() {
		return this.precision;
	}

	public void setPrecision(double precision) {
		this.precision = precision;
	}

	public boolean isHasz() {
		return this.hasz;
	}

	public void setHasz(boolean hasz) {
		this.hasz = hasz;
	}

	public Set<Layer> getLayers() {
		return this.layers;
	}

	public void setLayers(Set<Layer> layers) {
		this.layers = layers;
	}

}
