package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 28.10.2015 12:44:52 by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Track generated by hbm2java
 */
@Entity
@Table(name = "track", schema = "public")
public class Track implements java.io.Serializable {

	private String id;
	private Device device;
	private Date start;
	private Date end;

	public Track() {
	}

	public Track(String id, Device device, Date start, Date end) {
		this.id = id;
		this.device = device;
		this.start = start;
		this.end = end;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "device_id", nullable = false)
	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start", nullable = false, length = 29)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end", nullable = false, length = 29)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

}
