package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

/**
 * Track generated by hbm2java
 */
public class Track implements java.io.Serializable {

	private Serializable id;
	private Device device;
	private Date start;
	private Date end;

	public Track() {
	}

	public Track(Serializable id, Device device, Date start, Date end) {
		this.id = id;
		this.device = device;
		this.start = start;
		this.end = end;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public Device getDevice() {
		return this.device;
	}

	public void setDevice(Device device) {
		this.device = device;
	}

	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

}
