package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TransportationRoute generated by hbm2java
 */
public class TransportationRoute implements java.io.Serializable {

	private Serializable id;
	private Transportation transportation;
	private String name;
	private Date validFrom;
	private Date validUntil;
	private Set<Segment> segments = new HashSet<Segment>(0);
	private Set<Shedule> shedules = new HashSet<Shedule>(0);
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);

	public TransportationRoute() {
	}

	public TransportationRoute(Serializable id, Transportation transportation, Date validFrom) {
		this.id = id;
		this.transportation = transportation;
		this.validFrom = validFrom;
	}

	public TransportationRoute(Serializable id, Transportation transportation, String name, Date validFrom,
			Date validUntil, Set<Segment> segments, Set<Shedule> shedules, Set<Waypoint> waypoints) {
		this.id = id;
		this.transportation = transportation;
		this.name = name;
		this.validFrom = validFrom;
		this.validUntil = validUntil;
		this.segments = segments;
		this.shedules = shedules;
		this.waypoints = waypoints;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public Transportation getTransportation() {
		return this.transportation;
	}

	public void setTransportation(Transportation transportation) {
		this.transportation = transportation;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	public Date getValidUntil() {
		return this.validUntil;
	}

	public void setValidUntil(Date validUntil) {
		this.validUntil = validUntil;
	}

	public Set<Segment> getSegments() {
		return this.segments;
	}

	public void setSegments(Set<Segment> segments) {
		this.segments = segments;
	}

	public Set<Shedule> getShedules() {
		return this.shedules;
	}

	public void setShedules(Set<Shedule> shedules) {
		this.shedules = shedules;
	}

	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

}
