package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 17.11.2015 09:21:54 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransportationRoute generated by hbm2java
 */
@Entity
@Table(name = "transportation_route", schema = "public")
public class TransportationRoute implements java.io.Serializable {

	private UUID id;
	private Transportation transportation;
	private String name;
	private Date validFrom;
	private Date validUntil;
	private String operator;
	private String network;
	private String extRef;
	private String descFrom;
	private String descTo;
	private String desc;
	private String routeNo;
	private Set<Segment> segments = new HashSet<Segment>(0);
	private Set<Shedule> shedules = new HashSet<Shedule>(0);
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);

	public TransportationRoute() {
	}

	public TransportationRoute(UUID id, Transportation transportation, Date validFrom) {
		this.id = id;
		this.transportation = transportation;
		this.validFrom = validFrom;
	}

	public TransportationRoute(UUID id, Transportation transportation, String name, Date validFrom,
			Date validUntil, String operator, String network, String extRef, String descFrom, String descTo,
			String desc, String routeNo, Set<Segment> segments, Set<Shedule> shedules, Set<Waypoint> waypoints) {
		this.id = id;
		this.transportation = transportation;
		this.name = name;
		this.validFrom = validFrom;
		this.validUntil = validUntil;
		this.operator = operator;
		this.network = network;
		this.extRef = extRef;
		this.descFrom = descFrom;
		this.descTo = descTo;
		this.desc = desc;
		this.routeNo = routeNo;
		this.segments = segments;
		this.shedules = shedules;
		this.waypoints = waypoints;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transportation_id", nullable = false)
	public Transportation getTransportation() {
		return this.transportation;
	}

	public void setTransportation(Transportation transportation) {
		this.transportation = transportation;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_from", nullable = false, length = 29)
	public Date getValidFrom() {
		return this.validFrom;
	}

	public void setValidFrom(Date validFrom) {
		this.validFrom = validFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "valid_until", length = 29)
	public Date getValidUntil() {
		return this.validUntil;
	}

	public void setValidUntil(Date validUntil) {
		this.validUntil = validUntil;
	}

	@Column(name = "operator")
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "network")
	public String getNetwork() {
		return this.network;
	}

	public void setNetwork(String network) {
		this.network = network;
	}

	@Column(name = "ext_ref")
	public String getExtRef() {
		return this.extRef;
	}

	public void setExtRef(String extRef) {
		this.extRef = extRef;
	}

	@Column(name = "desc_from")
	public String getDescFrom() {
		return this.descFrom;
	}

	public void setDescFrom(String descFrom) {
		this.descFrom = descFrom;
	}

	@Column(name = "desc_to")
	public String getDescTo() {
		return this.descTo;
	}

	public void setDescTo(String descTo) {
		this.descTo = descTo;
	}

	@Column(name = "desc")
	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	@Column(name = "route_no")
	public String getRouteNo() {
		return this.routeNo;
	}

	public void setRouteNo(String routeNo) {
		this.routeNo = routeNo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportationRoute")
	public Set<Segment> getSegments() {
		return this.segments;
	}

	public void setSegments(Set<Segment> segments) {
		this.segments = segments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportationRoute")
	public Set<Shedule> getShedules() {
		return this.shedules;
	}

	public void setShedules(Set<Shedule> shedules) {
		this.shedules = shedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "transportationRoute")
	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

}
