package at.fhv.itm14.fhvgis.persistence.hibernate.objects;
// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Transportation generated by hbm2java
 */
public class Transportation implements java.io.Serializable {

	private Serializable id;
	private String name;
	private Float maxSpeed;
	private Set<TransportationRoute> transportationRoutes = new HashSet<TransportationRoute>(0);
	private Set<Segment> segments = new HashSet<Segment>(0);
	private Set<Waypoint> waypoints = new HashSet<Waypoint>(0);

	public Transportation() {
	}

	public Transportation(Serializable id) {
		this.id = id;
	}

	public Transportation(Serializable id, String name, Float maxSpeed, Set<TransportationRoute> transportationRoutes,
			Set<Segment> segments, Set<Waypoint> waypoints) {
		this.id = id;
		this.name = name;
		this.maxSpeed = maxSpeed;
		this.transportationRoutes = transportationRoutes;
		this.segments = segments;
		this.waypoints = waypoints;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getMaxSpeed() {
		return this.maxSpeed;
	}

	public void setMaxSpeed(Float maxSpeed) {
		this.maxSpeed = maxSpeed;
	}

	public Set<TransportationRoute> getTransportationRoutes() {
		return this.transportationRoutes;
	}

	public void setTransportationRoutes(Set<TransportationRoute> transportationRoutes) {
		this.transportationRoutes = transportationRoutes;
	}

	public Set<Segment> getSegments() {
		return this.segments;
	}

	public void setSegments(Set<Segment> segments) {
		this.segments = segments;
	}

	public Set<Waypoint> getWaypoints() {
		return this.waypoints;
	}

	public void setWaypoints(Set<Waypoint> waypoints) {
		this.waypoints = waypoints;
	}

}
