package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Serializable id;
	private String username;
	private String password;
	private Set<Device> devices = new HashSet<Device>(0);

	public User() {
	}

	public User(Serializable id, String username, String password) {
		this.id = id;
		this.username = username;
		this.password = password;
	}

	public User(Serializable id, String username, String password, Set<Device> devices) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.devices = devices;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Device> getDevices() {
		return this.devices;
	}

	public void setDevices(Set<Device> devices) {
		this.devices = devices;
	}

}
