package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 17.11.2015 09:21:54 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Waypoint generated by hbm2java
 */
@Entity
@Table(name = "waypoint", schema = "public")
public class Waypoint implements java.io.Serializable {

	private UUID id;
	private Transportation transportation;
	private Poi poi;
	private TransportationRoute transportationRoute;
	private int nrOfSatellites;
	private Date recordTime;
	private Double accuracy;
	private boolean valid;
	private Float speed;
	private Serializable position;
	private Set<Segment> segmentsForWaypointToId = new HashSet<Segment>(0);
	private Set<Segment> segmentsForWaypointFromId = new HashSet<Segment>(0);

	public Waypoint() {
	}

	public Waypoint(UUID id, int nrOfSatellites, Date recordTime, boolean valid, Serializable position) {
		this.id = id;
		this.nrOfSatellites = nrOfSatellites;
		this.recordTime = recordTime;
		this.valid = valid;
		this.position = position;
	}

	public Waypoint(UUID id, Transportation transportation, Poi poi, TransportationRoute transportationRoute,
			int nrOfSatellites, Date recordTime, Double accuracy, boolean valid, Float speed, Serializable position,
			Set<Segment> segmentsForWaypointToId, Set<Segment> segmentsForWaypointFromId) {
		this.id = id;
		this.transportation = transportation;
		this.poi = poi;
		this.transportationRoute = transportationRoute;
		this.nrOfSatellites = nrOfSatellites;
		this.recordTime = recordTime;
		this.accuracy = accuracy;
		this.valid = valid;
		this.speed = speed;
		this.position = position;
		this.segmentsForWaypointToId = segmentsForWaypointToId;
		this.segmentsForWaypointFromId = segmentsForWaypointFromId;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public UUID getId() {
		return this.id;
	}

	public void setId(UUID id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transportation_superv_id")
	public Transportation getTransportation() {
		return this.transportation;
	}

	public void setTransportation(Transportation transportation) {
		this.transportation = transportation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "poi_id")
	public Poi getPoi() {
		return this.poi;
	}

	public void setPoi(Poi poi) {
		this.poi = poi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transportation_route_superv_id")
	public TransportationRoute getTransportationRoute() {
		return this.transportationRoute;
	}

	public void setTransportationRoute(TransportationRoute transportationRoute) {
		this.transportationRoute = transportationRoute;
	}

	@Column(name = "nr_of_satellites", nullable = false)
	public int getNrOfSatellites() {
		return this.nrOfSatellites;
	}

	public void setNrOfSatellites(int nrOfSatellites) {
		this.nrOfSatellites = nrOfSatellites;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "record_time", nullable = false, length = 29)
	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	@Column(name = "accuracy", precision = 17, scale = 17)
	public Double getAccuracy() {
		return this.accuracy;
	}

	public void setAccuracy(Double accuracy) {
		this.accuracy = accuracy;
	}

	@Column(name = "valid", nullable = false)
	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	@Column(name = "speed", precision = 8, scale = 8)
	public Float getSpeed() {
		return this.speed;
	}

	public void setSpeed(Float speed) {
		this.speed = speed;
	}

	@Column(name = "position", nullable = false)
	public Serializable getPosition() {
		return this.position;
	}

	public void setPosition(Serializable position) {
		this.position = position;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "waypointByWaypointToId")
	public Set<Segment> getSegmentsForWaypointToId() {
		return this.segmentsForWaypointToId;
	}

	public void setSegmentsForWaypointToId(Set<Segment> segmentsForWaypointToId) {
		this.segmentsForWaypointToId = segmentsForWaypointToId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "waypointByWaypointFromId")
	public Set<Segment> getSegmentsForWaypointFromId() {
		return this.segmentsForWaypointFromId;
	}

	public void setSegmentsForWaypointFromId(Set<Segment> segmentsForWaypointFromId) {
		this.segmentsForWaypointFromId = segmentsForWaypointFromId;
	}

}
