package at.fhv.itm14.fhvgis.persistence.hibernate.objects;

// default package
// Generated 27.10.2015 14:09:10 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Waypoint generated by hbm2java
 */
public class Waypoint implements java.io.Serializable {

	private Serializable id;
	private GpsPosition gpsPosition;
	private Transportation transportation;
	private Poi poi;
	private TransportationRoute transportationRoute;
	private int nrOfSatellites;
	private Date recordTime;
	private Double accuracy;
	private boolean valid;
	private Set<Segment> segmentsForWaypointToId = new HashSet<Segment>(0);
	private Set<Segment> segmentsForWaypointFromId = new HashSet<Segment>(0);

	public Waypoint() {
	}

	public Waypoint(Serializable id, GpsPosition gpsPosition, int nrOfSatellites, Date recordTime, boolean valid) {
		this.id = id;
		this.gpsPosition = gpsPosition;
		this.nrOfSatellites = nrOfSatellites;
		this.recordTime = recordTime;
		this.valid = valid;
	}

	public Waypoint(Serializable id, GpsPosition gpsPosition, Transportation transportation, Poi poi,
			TransportationRoute transportationRoute, int nrOfSatellites, Date recordTime, Double accuracy,
			boolean valid, Set<Segment> segmentsForWaypointToId, Set<Segment> segmentsForWaypointFromId) {
		this.id = id;
		this.gpsPosition = gpsPosition;
		this.transportation = transportation;
		this.poi = poi;
		this.transportationRoute = transportationRoute;
		this.nrOfSatellites = nrOfSatellites;
		this.recordTime = recordTime;
		this.accuracy = accuracy;
		this.valid = valid;
		this.segmentsForWaypointToId = segmentsForWaypointToId;
		this.segmentsForWaypointFromId = segmentsForWaypointFromId;
	}

	public Serializable getId() {
		return this.id;
	}

	public void setId(Serializable id) {
		this.id = id;
	}

	public GpsPosition getGpsPosition() {
		return this.gpsPosition;
	}

	public void setGpsPosition(GpsPosition gpsPosition) {
		this.gpsPosition = gpsPosition;
	}

	public Transportation getTransportation() {
		return this.transportation;
	}

	public void setTransportation(Transportation transportation) {
		this.transportation = transportation;
	}

	public Poi getPoi() {
		return this.poi;
	}

	public void setPoi(Poi poi) {
		this.poi = poi;
	}

	public TransportationRoute getTransportationRoute() {
		return this.transportationRoute;
	}

	public void setTransportationRoute(TransportationRoute transportationRoute) {
		this.transportationRoute = transportationRoute;
	}

	public int getNrOfSatellites() {
		return this.nrOfSatellites;
	}

	public void setNrOfSatellites(int nrOfSatellites) {
		this.nrOfSatellites = nrOfSatellites;
	}

	public Date getRecordTime() {
		return this.recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	public Double getAccuracy() {
		return this.accuracy;
	}

	public void setAccuracy(Double accuracy) {
		this.accuracy = accuracy;
	}

	public boolean isValid() {
		return this.valid;
	}

	public void setValid(boolean valid) {
		this.valid = valid;
	}

	public Set<Segment> getSegmentsForWaypointToId() {
		return this.segmentsForWaypointToId;
	}

	public void setSegmentsForWaypointToId(Set<Segment> segmentsForWaypointToId) {
		this.segmentsForWaypointToId = segmentsForWaypointToId;
	}

	public Set<Segment> getSegmentsForWaypointFromId() {
		return this.segmentsForWaypointFromId;
	}

	public void setSegmentsForWaypointFromId(Set<Segment> segmentsForWaypointFromId) {
		this.segmentsForWaypointFromId = segmentsForWaypointFromId;
	}

}
